"""empty message

Revision ID: 06397aded7fd
Revises: 88106d301a40
Create Date: 2016-03-15 00:39:26.065911

"""

# revision identifiers, used by Alembic.
revision = '06397aded7fd'
down_revision = '88106d301a40'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
