"""empty message

Revision ID: 08c3efcf9d2c
Revises: None
Create Date: 2016-06-15 02:09:57.588242

"""

# revision identifiers, used by Alembic.
revision = '08c3efcf9d2c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topics')
    op.drop_column('posts', 'topic_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('topic_id', sa.INTEGER(), nullable=True))
    op.create_table('topics',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###
