"""empty message

Revision ID: 4046a3f75032
Revises: 13647876f6d4
Create Date: 2016-03-19 22:56:07.791453

"""

# revision identifiers, used by Alembic.
revision = '4046a3f75032'
down_revision = '13647876f6d4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'body_html')
    ### end Alembic commands ###
